[package]
name = "risk-hound"
version = "0.1.0"
edition = "2021"
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
hound-services = { workspace = true, features = ["tracing"] }
tracing.workspace = true
